### PR TITLE
save and restore `CallContext` for host tasks

### LINKED ISSUE #10: Owned resource seemingly escaping scope
This issue looks very similar to #2, encountered while implementing `wasi:sockets` TCP

On https://github.com/bytecodealliance/wasip3-prototyping/commit/c347376e66784b1a3560f3a5efb537961452832a

apply:
```diff
diff --git a/crates/wasi/tests/all/p3/sockets.rs b/crates/wasi/tests/all/p3/sockets.rs
index 32ce157b5..3ebab90ee 100644
--- a/crates/wasi/tests/all/p3/sockets.rs
+++ b/crates/wasi/tests/all/p3/sockets.rs
@@ -14,7 +14,6 @@ async fn sockets_0_3_tcp_bind() -> anyhow::Result<()> {
     run(SOCKETS_0_3_TCP_BIND_COMPONENT).await
 }
 
-#[ignore = "fails with `failed to get promise` due to `cannot remove owned resource while borrowed`"]
 #[test_log::test(tokio::test(flavor = "multi_thread"))]
 async fn sockets_0_3_tcp_connect() -> anyhow::Result<()> {
     run(SOCKETS_0_3_TCP_CONNECT_COMPONENT).await
@@ -26,13 +25,11 @@ async fn sockets_0_3_tcp_sample_application() -> anyhow::Result<()> {
     run(SOCKETS_0_3_TCP_SAMPLE_APPLICATION_COMPONENT).await
 }
 
-#[ignore = "fails with `failed to get promise` due to `cannot remove owned resource while borrowed`"]
 #[test_log::test(tokio::test(flavor = "multi_thread"))]
 async fn sockets_0_3_tcp_sockopts() -> anyhow::Result<()> {
     run(SOCKETS_0_3_TCP_SOCKOPTS_COMPONENT).await
 }
 
-#[ignore = "fails with `failed to get promise` due to `cannot remove owned resource while borrowed`"]
 #[test_log::test(tokio::test(flavor = "multi_thread"))]
 async fn sockets_0_3_tcp_states() -> anyhow::Result<()> {
     run(SOCKETS_0_3_TCP_STATES_COMPONENT).await

```

(note that `--ignored` will surface #9 )

A way to reproduce this error is:

```
cargo test -p wasmtime-wasi p3
```

```
Error: failed to get promise

Caused by:
    0: error while executing at wasm backtrace:
           0: 0x69a8 - sockets_0_3_tcp_sockopts-233e74cc39a42d17.wasm!_ZN107_$LT$test_programs..p3..wasi..sockets..types..TcpSocket$u20$as$u20$test_programs..p3.._rt..WasmResource$GT$4drop17h879d19b1709e8ac5E
           1: 0x3d36 - sockets_0_3_tcp_sockopts-233e74cc39a42d17.wasm!_ZN83_$LT$test_programs..p3.._rt..Resource$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$4drop17h2506d9bc38b6a8a9E
           2: 0x3cb1 - sockets_0_3_tcp_sockopts-233e74cc39a42d17.wasm!_ZN4core3ptr111drop_in_place$LT$test_programs..p3.._rt..Resource$LT$test_programs..p3..wasi..sockets..types..TcpSocket$GT$$GT$17h16b0f941d4362be1E
           3: 0x3a44 - sockets_0_3_tcp_sockopts-233e74cc39a42d17.wasm!_ZN4core3ptr71drop_in_place$LT$test_programs..p3..wasi..sockets..types..TcpSocket$GT$17h1c504c1981faaa4dE
           4: 0xce5b - sockets_0_3_tcp_sockopts-233e74cc39a42d17.wasm!_ZN24sockets_0_3_tcp_sockopts28test_tcp_sockopt_inheritance28_$u7b$$u7b$closure$u7d$$u7d$17hf5d635c0f7dfca1fE
           5: 0xacf4 - sockets_0_3_tcp_sockopts-233e74cc39a42d17.wasm!_ZN105_$LT$sockets_0_3_tcp_sockopts..Component$u20$as$u20$test_programs..p3..exports..wasi..cli..run..Guest$GT$3run28_$u7b$$u7b$closure$u7d$$u7d$17h527a6b4cc22b09cbE
           6: 0x1584d - sockets_0_3_tcp_sockopts-233e74cc39a42d17.wasm!_ZN13test_programs2p37exports4wasi3cli3run16_export_run_cabi28_$u7b$$u7b$closure$u7d$$u7d$17h765d32affe652101E
           7: 0x16078 - sockets_0_3_tcp_sockopts-233e74cc39a42d17.wasm!_ZN102_$LT$futures_util..future..future..map..Map$LT$Fut$C$F$GT$$u20$as$u20$core..future..future..Future$GT$4poll17h5c9a0cf8d456dfaeE
           8: 0xfad2 - sockets_0_3_tcp_sockopts-233e74cc39a42d17.wasm!_ZN97_$LT$futures_util..future..future..Map$LT$Fut$C$F$GT$$u20$as$u20$core..future..future..Future$GT$4poll17h7b12d62491323690E
           9: 0x36fa9 - sockets_0_3_tcp_sockopts-233e74cc39a42d17.wasm!_ZN72_$LT$core..pin..Pin$LT$P$GT$$u20$as$u20$core..future..future..Future$GT$4poll17hf9a99cb7122f6625E
          10: 0x36812 - sockets_0_3_tcp_sockopts-233e74cc39a42d17.wasm!_ZN117_$LT$futures_util..stream..futures_unordered..FuturesUnordered$LT$Fut$GT$$u20$as$u20$futures_core..stream..Stream$GT$9poll_next17hfe88b17ee4c8b525E
          11: 0x37836 - sockets_0_3_tcp_sockopts-233e74cc39a42d17.wasm!_ZN12futures_util6stream6stream9StreamExt15poll_next_unpin17hc0f93e4c8bad6624E
          12: 0x34f75 - sockets_0_3_tcp_sockopts-233e74cc39a42d17.wasm!_ZN14wit_bindgen_rt13async_support4poll17h47ca04e0ec551bc5E
          13: 0x35454 - sockets_0_3_tcp_sockopts-233e74cc39a42d17.wasm!_ZN14wit_bindgen_rt13async_support8callback17h3dbe2e0f54a44d68E
          14: 0x248d0 - sockets_0_3_tcp_sockopts-233e74cc39a42d17.wasm!_ZN13test_programs2p37exports4wasi3cli3run14__callback_run17hb6733d43c2ab0f54E
          15: 0x155e8 - sockets_0_3_tcp_sockopts-233e74cc39a42d17.wasm![callback][async]wasi:cli/run@0.3.0#run
       note: using the `WASMTIME_BACKTRACE_DETAILS=1` environment variable may show more debugging information
    1: cannot remove owned resource while borrowed
```

Even though encountered working off #9 , I think this issue was not introduced by the PR, as I have seen it before

### PR DESCRIPTION
**Pull request by dicej**
We were already doing this for guest tasks, but I missed doing it for host tasks, leading to "cannot remove owned resource while borrowed" errors.

Fixes #10.

### CODE REVIEW

File: crates/wasmtime/src/runtime/component/concurrent.rs [hunk 1]
```diff
@@ -1456,6 +1456,55 @@ pub(crate) fn first_poll<T, R: Send + Sync + 'static>(
...
         .push_child(HostTask { caller_instance }, caller)?;
+
+    // Here we wrap the future in a `future::poll_fn` to ensure that we restore
+    // and save the `CallContext` for this task before and after polling it,
+    // respectively.  This involves unsafe shenanigans in order to smuggle the
+    // store pointer into the wrapping future, alas.
+
+    struct Ptr<T: ?Sized>(*mut T);
+    unsafe impl<T: ?Sized> Send for Ptr<T> {}
+    unsafe impl<T: ?Sized> Sync for Ptr<T> {}
```
Comment (vados-cosmonic) [inline crates/wasmtime/src/runtime/component/concurrent.rs:1467]: NIT: Does it make sense to reuse `VMStoreRawPtr` (after opening it up to `pub(crate)` usage)?

Comment (dicej) [reply crates/wasmtime/src/runtime/component/concurrent.rs:1467]: Ah, good call; I didn't know about that.  I'll push an update when I get a chance.

**Comment by dicej** [comment]
I'm going crazy juggling so many branches, so I'm going to go ahead and merge this.  I promise to fix any regressions it may cause!
